### PR TITLE
Add option to disable driver version check

### PR DESCRIPTION
**Pull request by mYmNeo**
Signed-off-by: thomassong <thomassong@tencent.com>

### CODE REVIEW

**Comment by 3XX0** [comment]
Why do you need to do this?
Also, we are in code freeze until 2.0 comes out so I don't think we can merge this PR.

**Comment by mYmNeo** [comment]
Most time user do not need to know what version the driver is, they just want to mount the driver volume. If we check version strictly, user have to know exactly what version of driver this machine has installed, this makes users have some knowledge about how to find driver version. To make it easy to use, we can skip check version strictly.

**Comment by flx42** [comment]
> If we check version strictly, user have to know exactly what version of driver this machine has installed, this makes users have some knowledge about how to find driver version.

I don't understand this. The user doesn't need to know which exact version he is using. Could you explain in more details?

**Comment by mYmNeo** [comment]
@flx42 Sorry for not describing the detail of our scenario. We don't use your `nvidia-docker` only `nvidia-docker-plugin`. I've read your source code and find that `nvidia-docker` create volume by [this](https://github.com/NVIDIA/nvidia-docker/blob/master/src/nvidia-docker/main.go#L83). This function can identify the right nvidia driver version, and pass it to `nvidia-docker-plugin`. Then the volume plugin try to [check the volume version](https://github.com/NVIDIA/nvidia-docker/blob/master/src/nvidia-docker-plugin/plugin_volume.go#L73). If version is matched, everything will go on, otherwise it'll raise error. Considering our scenario, we just use your volume plugin, so users have to pass the right docker options containing the right driver version to the local or remote volume plugin to make create operation work well.

**Pull request closed without merging**
