### PR TITLE
nvidia.go: ask if nvidia-modprobe is installed

### PR DESCRIPTION
**Pull request by scpeters**
Improve error message with hint about `nvidia-modprobe` being installed. Related to #125

### CODE REVIEW

**Comment by flx42** [comment]
@3XX0 any objection?

Even if this patch is tiny, we require a CLA before accepting any contribution:
https://github.com/NVIDIA/nvidia-docker#issues-and-contributing
Or, since the change is small enough, I can just author the fix myself ;)

**Comment by scpeters** [comment]
I'll get back to you shortly about the CLA.

**Comment by 3XX0** [comment]
Nope good to go!

**Comment by scpeters** [comment]
Ok, I submitted a CLA by emailing the address listed in the Readme

**Comment by flx42** [comment]
Done, thanks for your submission and for sending the CLA!

**Comment by scpeters** [comment]
No problem, I'm looking forward to using this instead of installing specific driver versions in our docker files!

**Comment by amacneil** [comment]
👍 nice, this error had me stumped for a while.

**Pull request closed without merging**
