### PR TITLE
Add rhel7.8 support

### PR DESCRIPTION
**Pull request by cdesiniotis**
Signed-off-by: Christopher Desiniotis <cdesiniotis@nvidia.com>

### CODE REVIEW

**Comment by cdesiniotis** [comment]
@nvjmayo

**Comment by cdesiniotis** [comment]
@RenaudWasTaken @klueska Addresses #1319 and #1354

**Comment by klueska** [comment]
Hi @cdesiniotis, the reason we haven’t added rhel7.8 support yet is because we don’t have the internal infrastructure set up to properly test on rhel7.8 yet. Only once this is in place will we add official rhel7.8 support. Until then, the best we can recommend is to install from rhel7.7 and hope it works well enough (without official support).

**Comment by cdesiniotis** [comment]
@klueska Okay makes sense. Thanks for the info, I will close

**Pull request closed without merging**
