### PR TITLE
Split cuda image into cuda-runtime and cuda-devel

### PR DESCRIPTION
**Pull request by flx42**
Fixes: #12 

Submitting this one for review by @3XX0 and @ruffsl since it touches almost every file in the repository.
Now we have two flavors of each CUDA toolkit: cuda-runtime and cuda-devel.
* **cuda-runtime** only contains the CUDA shared libraries. If you want to use a pre-built package of a project (e.g. a binary or a pip package), then it should work fine.
- **cuda-devel** adds the header files, static CUDA libraries, the compiler toolchain, the debugging tools. 
For convenience, this image should be tagged **cuda** by users. This image doesn't include documentation, samples and visual tools; thus the image is still significantly smaller than the previous **cuda** image.

Here are the size of the images right now:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
cuda-devel          7.0                 8c9f67f29ae9        15 minutes ago      1.194 GB
cuda-runtime        7.0                 2ad0a2582ca9        19 minutes ago      539.6 MB
cuda-devel          6.5                 cb3358301dbd        24 minutes ago      1.012 GB
cuda-runtime        6.5                 9754b1ebf287        26 minutes ago      428.9 MB
cuda-devel          7.5                 2cb11b823f01        31 minutes ago      1.223 GB
cuda-runtime        7.5                 376f27b3595d        34 minutes ago      561.7 MB
ubuntu              14.04               e9ae3c220b23        10 days ago         187.9 MB
```

### CODE REVIEW

**Comment by ruffsl** [comment]
So, you'd want to make a separate repository for cuda-devel vs cuda-runtime?
I was thinking you could split that by a tag to just reduce the fragmentation:

>Supported tags and respective Dockerfile links
- [`7.5-runtime` (*ubuntu-14.04/cuda/7.5/runtime/Dockerfile*)](https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/cuda/7.5/runtime/Dockerfile)
- [`7.5-devel`, `7.5`, `latest` (*ubuntu-14.04/cuda/7.5/devel/Dockerfile*)](https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/cuda/7.5/devel/Dockerfile)
- [`7.0-runtime` (*ubuntu-14.04/cuda/7.0/runtime/Dockerfile*)](https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/cuda/7.0/runtime/Dockerfile)
- [`7.0-devel`, `7.0` (*ubuntu-14.04/cuda/7.0/devel/Dockerfile*)](https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/cuda/7.0/devel/Dockerfile)
- [`6.5-runtime` (*ubuntu-14.04/cuda/6.5/runtime/Dockerfile*)](https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/cuda/6.5/runtime/Dockerfile)
- [`6.5-devel`, `6.5` (*ubuntu-14.04/cuda/6.5/devel/Dockerfile*)](https://github.com/NVIDIA/nvidia-docker/blob/master/ubuntu-14.04/cuda/6.5/devel/Dockerfile)

Keep in mind where you'd want to attach the `cudnn` image later though, whether it be a tag or repo in itself. I'm not sure of the best place to put it. Perhaps `7.0-runtime-cudnn`, and folks who want devel + cudnn just rebuild devel pointing to it?

**Comment by flx42** [comment]
I don't want to commit to a particular layout or tag strategy for the Docker Hub just yet. If we had done so already we will be in even more trouble right now since we are changing everything. I expect this will happen again one or multiple times.
Without considering the Docker Hub, I think the current layout makes sense and avoid having too many folder indirections.
But in the end, I'm don't expect us to have separate repositories for cuda-devel and cuda-runtime or even for cudnn, I don't think that's a frequent approach.

**Comment by 3XX0** [comment]
Here is a potential layout
Maybe cuDNN should be part of the CUDA repo though

> **CUDA**
- [`runtime-7.5` (*ubuntu-14.04/cuda-runtime/7.5/Dockerfile*)]()
- [`devel-7.5`, `7.5`, `latest` (*ubuntu-14.04/cuda-devel/7.5/Dockerfile*)]()
- [`runtime-7.0` (*ubuntu-14.04/cuda-runtime/7.0/Dockerfile*)]()
- [`devel-7.0`, `7.0` (*ubuntu-14.04/cuda-devel/7.0/Dockerfile*)]()
- [`runtime-6.5` (*ubuntu-14.04/cuda-runtime/6.5/Dockerfile*)]()
- [`devel-6.5`, `6.5` (*ubuntu-14.04/cuda-devel/6.5/Dockerfile*)]()

> **cuDNN**
- [`runtime-v2-7.0`, (*ubuntu-14.04/cuda-runtime/7.0/cudnn-v2/Dockerfile*)]()
- [`devel-v2-7.0`, `v2-7.0`, `latest` (*ubuntu-14.04/cuda-devel/7.0/cudnn-v2/Dockerfile*)]()

**Comment by ruffsl** [comment]
Well, either way @flx42 , the number of leaf folders made is the same: 2x3=3x2. I'm just thinking you may want to structure by os->v#->app. Its [common](https://hub.docker.com/_/node/) [to see](https://hub.docker.com/_/php/) most tag  structures set version number as the prefix, and instance specifics as the postfix. You could play around with other tag conventions, but it could get a little [verbose](https://hub.docker.com/_/java/). Can't hurt to have the folder tree structure mimic the branching tag hierarchy. 

Playing devils advocate, @3XX0, what would be some cases for the opposite (for a cuDNN repo)?

**Comment by 3XX0** [comment]
I was following our package convention (i.e cuda-X-version) but either way is fine.
Not sure what's the official way of doing it

**Comment by 3XX0** [comment]
After discussion:

> **CUDA**
- [`7.5-runtime`, `runtime` (*ubuntu-14.04/cuda/7.5/runtime/Dockerfile*)]()
- [`7.5-devel`, `7.5`, `devel`, `latest` (*ubuntu-14.04/cuda/7.5/devel/Dockerfile*)]()
- [`7.0-runtime` (*ubuntu-14.04/cuda/7.0/runtime/Dockerfile*)]()
- [`7.0-devel`, `7.0` (*ubuntu-14.04/cuda/7.0/devel/Dockerfile*)]()
- [`6.5-runtime` (*ubuntu-14.04/cuda/6.5/runtime/Dockerfile*)]()
- [`6.5-devel`, `6.5` (*ubuntu-14.04/cuda/6.5/devel/Dockerfile*)]()

> **CUDA + cuDNN**
- [`7.0-cudnn2-runtime`, `cudnn2-runtime`, `cudnn-runtime` (*ubuntu-14.04/cuda/7.0/runtime/cudnn2.0/Dockerfile*)]()
- [`7.0-cudnn2-devel`, `cudnn2-devel`, `cudnn-devel`, `cudnn` (*ubuntu-14.04/cuda/7.0/devel/cudnn2.0/Dockerfile*)]()

**Comment by ruffsl** [comment]
@3XX0 , what you've described looks great, I am in agreement. I like the flexibility offered to users by making both a runtime and devel version of cuDNN, and the pattern of tag aliases is very clear. It's ok it have a good amount of tags, as the build process is automated, maintenance is quite low once we get it down, and it lets users a pick what the need.

Just looked through b45091a and it LGTM! One suggestion is that perhaps you'd want to create a simple Makefile to build, tag, pull, rm all the growing number of tags, like this [Makefile](https://github.com/osrf/docker_images/blob/master/ros/indigo/Makefile). They are quite simple, and users can quickly mod it as needed.

**Comment by ruffsl** [comment]
@3XX0 , if you changed those links point to their respective Dockerfiles, I believe that bullet markdown list would be a useful addition to the beginning of this repo's README.md.

**Comment by 3XX0** [comment]
Yes, we're going to update all the documentation fairly soon.
In the meantime I put it on the HUB documentation: https://hub.docker.com/r/nvidia/cuda/

**Comment by ruffsl** [comment]
I think if you make that repo automated, you could have it render documentation on the docker-repo page using the README.md from the git-repo. See [Understand the build process](https://docs.docker.com/docker-hub/builds/#understand-the-build-process).

**Comment by flx42** [comment]
@ruffsl  I added a Makefile like you suggested :)
next step is #18

**Comment by ruffsl** [comment]
That's a great Makefile , I think I might mimic it :D

**Pull request closed without merging**
