### PR TITLE
Fan speed info

### PR DESCRIPTION
**Pull request by prettynatty**

### CODE REVIEW

**Comment by flx42** [comment]
We don't know many people that are using our device monitoring endpoints :)
May I ask what you are using it for? And why do you need the fan speed?

**Comment by prettynatty** [comment]
Hi @flx42 !
We are implementing an utility for centralized monitoring and (in near future) control of distributed CUDA cluster. We love go for system utilities and we are utilizing docker heavily, that's why it happened that I stumbled upon that awesome project and adopted it into our infrastructure.

**Comment by polarathene** [comment]
Another project that I believe monitors the GPU to know if it should reduce workload to maintain a temperature threshold is Hashcat. Not sure if they have a docker version yet, but something like this might affect such a feature being supported?

**Comment by mdlayher** [comment]
I'd also like to chime in.  I'm interested in building a prometheus.io exporter for nvidia GPUs, and these kinds of stats are useful to me in that context.

**Comment by prettynatty** [comment]
@mdlayher take a look at my project: https://github.com/breakinghash/nvidia-exporter

**Comment by 3XX0** [comment]
Not sure, shouldn't we create a new repo for the Go bindings?

**Comment by mdlayher** [comment]
Since the Go bindings are useful outside of this repository, yep, I'd split out a new one and vendor in the version you need here.

**Comment by 3XX0** [comment]
Closing since this is not applicable to 2.0. We'll probably provide Go bindings in a separate repo.

**Pull request closed without merging**
