### PR TITLE
updated README to indicate that ubuntu20.04 is supported.

### PR DESCRIPTION
**Pull request by mustaphazorgati**
https://github.com/NVIDIA/nvidia-docker/issues/1204

### CODE REVIEW

**Comment by gemfield** [comment]
Not exactly...

`gemfield@ai05:~$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
gpg: no valid OpenPGP data found.`

**Comment by gemfield** [comment]
It turns out if I run this command on Ubuntu 18.04, I got:
```bash
gemfield@AI01:/bigdata2/dataset$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFnNWDEBEACiX68rxIWvqH3h2GykO25oK9BAqV8fDtb6lXEbw3eKx4g87BRz
M3DQBA0S0IfkQ72ovJ33H50+gVTXuu+Zme5muWk72m3pApccZVDLqdzYlpWPruNb
MC+IlWr70yo8Jw8Zr1ihbWjFvMbDJTkgqPt2djNq3xxvdiKoZlgnpLRKIpSu9iBQ
......
```
While I run this command on Ubuntu 20.04, I got no output:
```bash
gemfield@ai05:~$ curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey
gemfield@ai05:~$ 
```

**Comment by mustaphazorgati** [comment]
@flx42 @RenaudWasTaken can you please answer? :) This is probably dealt with <5 min

**Comment by RenaudWasTaken** [comment]
Hello!

Thanks for your contribution! Can you open an issue against the gitlab repo, this repository is mirrored from: https://gitlab.com/nvidia/container-toolkit/nvidia-docker

Thanks!

**Comment by RenaudWasTaken** [comment]
Ended up updating the README in https://github.com/NVIDIA/nvidia-docker/commit/166fa7ffb23502da8f0b3364c92430d42d267f5b

Thanks again for the contribution, it should be a lot faster if you make it against gitlab :)

**Pull request closed without merging**
