### PR TITLE
Ubuntu 14.04 and CUDA 6.5

### PR DESCRIPTION
**Pull request by yeison**
I tested this on my system and it seems to work.

### CODE REVIEW

**Comment by flx42** [comment]
Please send us the signed CLA before we can accept your contribution
https://github.com/NVIDIA/nvidia-docker#issues-and-contributing

Thanks!

**Comment by yeison** [comment]
To reply to the question in the other thread- the reason I want to use 6.5 is because I have an old NVIDIA card that isn't compatible with the 352 driver.

**Comment by flx42** [comment]
Which GPU do you have?

**Comment by yeison** [comment]
Here are the details of the card I have.  I think I'll just buy a new card.  I ran into issues running the code I wanted to run (CUBLAS_STATUS_EXECUTION_FAILED)

Device 0: "GeForce 8400GS"
  CUDA Driver Version / Runtime Version          6.5 / 6.5
  CUDA Capability Major/Minor version number:    1.2
  Total amount of global memory:                 1024 MBytes (1073545216 bytes)
  ( 2) Multiprocessors, (  8) CUDA Cores/MP:     16 CUDA Cores
  GPU Clock rate:                                1238 MHz (1.24 GHz)
  Memory Clock rate:                             600 Mhz
  Memory Bus Width:                              64-bit
  Maximum Texture Dimension Size (x,y,z)         1D=(8192), 2D=(65536, 32768), 3D=(2048, 2048, 2048)
  Maximum Layered 1D Texture Size, (num) layers  1D=(8192), 512 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(8192, 8192), 512 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       16384 bytes
  Total number of registers available per block: 16384
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  1024
  Maximum number of threads per block:           512
  Max dimension size of a thread block (x,y,z): (512, 512, 64)
  Max dimension size of a grid size    (x,y,z): (65535, 65535, 1)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             256 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      No
  Device PCI Bus ID / PCI location ID:           2 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 6.5, CUDA Runtime Version = 6.5, NumDevs = 1, Device0 = GeForce 8400GS
Result = PASS

**Comment by flx42** [comment]
Wow, that's an old GPU indeed, you won't be able to run a lot of CUDA code with this.
But we can still merge this PR if you rebase it and send us the CLA, otherwise I can add 6.5 support myself.

**Comment by 3XX0** [comment]
Um Tesla architecture on CUDA 6.5-19, @flx42 you're sure about this ?

**Comment by flx42** [comment]
Oh no it won't work, but I would be happy to accept the contribution anyway if he fixes the PR.

**Comment by yeison** [comment]
I don't have access to a printer at the moment to sign the CLA.  Feel free to add the 6.5 support with my PR.

**Comment by yeison** [comment]
Yea new GPU received today.  I'm excited to put this baby to the test:

Device 0: "GeForce GTX 950"
  CUDA Driver Version / Runtime Version          7.5 / 7.5
  CUDA Capability Major/Minor version number:    5.2
  Total amount of global memory:                 2048 MBytes (2147287040 bytes)
  ( 6) Multiprocessors, (128) CUDA Cores/MP:     768 CUDA Cores
  GPU Max Clock rate:                            1266 MHz (1.27 GHz)
  Memory Clock rate:                             3305 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 1048576 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 2 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 7.5, CUDA Runtime Version = 7.5, NumDevs = 1, Device0 = GeForce GTX 950
Result = PASS

**Pull request closed without merging**
