### PR TITLE
Add support for cross-device volumes

### LINKED ISSUE #47: Volume setup fails across device boundaries
When your Docker graph is not mounted on the same device as `/usr/bin` etc., you see these sorts of errors during `nvidia-docker volume setup`:

`Error: link /usr/bin/nvidia-cuda-mps-control /mnt/docker/volumes/nvidia_driver_352.79/_data/bin/nvidia-cuda-mps-control: invalid cross-device link`

This is caused by hard-linking the binaries here: https://github.com/NVIDIA/nvidia-docker/blob/e7b792253f0d0ad1bed19a3236db0ac58aaf9563/tools/src/nvidia/volumes.go#L179

### PR DESCRIPTION
**Pull request by mvollrath**
Hard-linking will fail when Docker graph is on an alternate mount point.  Fallback to copy whenever it fails.

Fixes #47

### CODE REVIEW

**Comment by seanbell** [comment]
Why is a symlink not possible?  Why must it be hardlink or copy?

**Comment by 3XX0** [comment]
Symlinks are relative to the new container namespace and won't cross its boundaries.
We are actually using them to create the sonames in the container (https://github.com/NVIDIA/nvidia-docker/blob/master/tools/src/nvidia/volumes.go#L189).

**Comment by mvollrath** [comment]
I've updated this based on feedback in #47 

Copy fallback is now only used for `volume setup`.

**Comment by 3XX0** [comment]
Merged! Thanks for the PR @mvollrath

**Comment by mvollrath** [comment]
Thanks, but you should remove the vim .swp file and add `*.swp` to `.gitignore` to prevent more accidental swapfile commits.

**Comment by flx42** [comment]
Ouch, thank you for noticing!

**Pull request closed without merging**
