### PR TITLE
Implement cuDNN, Caffe(dev), Digits(dev) Dockerfiles for CentOS 7

### PR DESCRIPTION
**Pull request by edsonke**
Hi, I've implemented some docker files which will help user using Digits under CentOS 7, but still need your kindly review to check these commits.
User can use DIGITS dev-server located in /tmp with these commits.

Following are some more detail about these commits
1. I install the cuDNN library with Ubuntu deb files. As far as I know, user have to register to Nvidia forum to get .rpm , hence I did some trick(transform .deb files to .rpm using ruby-fpm) to install Ubuntu deb files instead of asking user to get the files.
2. I build Caffe and DIGITS with these Dockerfiles instead of installing the .deb files provided by Nvidia directly. There are reasons to do this. First, both Caffe and DIGITS depends on many stuffs which might not as same as Ubuntu and their scripts inside .deb installation are incompatible to CentOS totally.

### CODE REVIEW

**Comment by flx42** [comment]
For cuDNN, here's a small hint:
http://developer.download.nvidia.com/compute/redist/cudnn/v4/cudnn-7.0-linux-x64-v4.0-prod.tgz

That's what we used to do:
https://github.com/NVIDIA/nvidia-docker/blob/af05565e48b12dfbb7eb780e6c16038ac6ff3916/ubuntu-14.04/cuda/7.5/devel/cudnn4/Dockerfile
But we used `v4.0-rc.tgz`, now you can use `v4.0-prod.tgz`

**Comment by edsonke** [comment]
Hi @flx42 ,
Appreciate for your comment, it has been updated as your recommendation.

BR

**Comment by flx42** [comment]
Sorry, I don't have a lot of time to review this PR.
Quick question for now: why do you need DIGITS on CentOS?

For CUDA and Caffe I can understand, since they can be used as base image for other projects. But for DIGITS I'm not sure I see the use case.

**Comment by edsonke** [comment]
Hi @flx42 ,
Sorry for late reply. I think there are at least two reasons to have these stuff:
* For enterprise version just starting from CenOS widerspread.
* And another reason for NV they already think DIGITS could be inference engine not only training such that docker support for CentOS is coming to confront it.

Best reagards

**Comment by flx42** [comment]
@edsonke sorry for letting the PR rot! I merged your cuDNN patch and the missing packages.
We decided to not include CentOS versions of Caffe and DIGITS for now, but feel free to continue maintaining your own versions using the new images.

**Pull request closed without merging**
